# Book settings

title: Patient Treatment Classification Project
author: Stephanie Ta
logo: logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://stephanie-ta.github.io/patient_treatment_classification_project_online/Introduction.html
  branch: main

# Add GitHub buttons to your book
# See https://github.com/Stephanie-Ta/patient_treatment_classification_project_online
html:
  use_issues_button: false
  use_repository_button: true
