name: classification_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair==5.2.0
  - conda==23.11.0
  - jupyter-book==0.15.1
  - jupyterlab==4.0.10
  - matplotlib==3.8.2
  - numpy==1.26.3
  - pandas==2.2.0
  - python=3.11
  - scikit-learn==1.4.0